//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionVerifyLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Tdate { get; set; }
        public Nullable<decimal> VerifiedAMount { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
    }
}
