//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string EmployeeNo { get; set; }
        public string EmployeeName { get; set; }
        public int DGId { get; set; }
        public int DeptId { get; set; }
        public int Religion { get; set; }
        public int Nationality { get; set; }
        public short MaritialStatus { get; set; }
        public System.DateTime DateOfJoin { get; set; }
        public int BranchId { get; set; }
        public short Gender { get; set; }
        public short BloodGroup { get; set; }
        public byte[] Photo { get; set; }
        public int Initials { get; set; }
        public System.DateTime PostedOn { get; set; }
        public int PostedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public short Status { get; set; }
    }
}
