//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiscalYear1
    {
        public short FYID { get; set; }
        public string FyName { get; set; }
        public System.DateTime StartDt { get; set; }
        public System.DateTime EndDt { get; set; }
    }
}
