//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuTemplate()
        {
            this.MenuVsTemplates = new HashSet<MenuVsTemplate>();
        }
    
        public int MenuTemplateId { get; set; }
        public string MTName { get; set; }
        public int DesignationId { get; set; }
        public int PostedBy { get; set; }
        public System.DateTime PostedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuVsTemplate> MenuVsTemplates { get; set; }
    }
}
