//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuMain
    {
        public int MenuId { get; set; }
        public string MenuCaption { get; set; }
        public int PMenuId { get; set; }
        public byte[] Image { get; set; }
        public int MenuOrder { get; set; }
        public bool IsGroup { get; set; }
        public bool IsEnable { get; set; }
        public bool IsContextMenu { get; set; }
        public string Controler { get; set; }
        public string Acton { get; set; }
    }
}
