//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParamValue
    {
        public int PId { get; set; }
        public byte DTId { get; set; }
        public string PDescription { get; set; }
        public string PValue { get; set; }
    
        public virtual DataType DataType { get; set; }
        public virtual Param Param { get; set; }
        public virtual ParamScript ParamScript { get; set; }
    }
}
