//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionCollection
    {
        public int SubsCollId { get; set; }
        public Nullable<int> CustId { get; set; }
        public int SubsId { get; set; }
        public Nullable<int> CollectorId { get; set; }
        public Nullable<int> CollectionTypeId { get; set; }
        public Nullable<decimal> CollectionAmt { get; set; }
        public Nullable<decimal> DiscountAmt { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
        public Nullable<int> Fyid { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
