//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WasteCollDaySetupCustAuto
    {
        public int Id { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> CollwkDay { get; set; }
        public Nullable<int> CollectionNotificationTypeId { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CollectorArriveDate { get; set; }
        public Nullable<int> CollectorId { get; set; }
        public Nullable<int> postedby { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
    }
}
